# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8d07d317488aad6e73df1ddbbe9badaa5262b2b4002fa1e7680c2f7b787bd0e0ab0b3f98bbe5ce872aa8f905f6f9e08c3e606e5e0fd780d24e9181ee25b7a3c

test:
  secret_key_base: 14defd3e56624aab3a485b39764ac3976e0cb1d815d4266533b98e5458a7b3ee9d967922e52f9fdc97fca3f589dc35235a23b5be66e80293fe767962555d111d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
