force_p_newlines : false
force_br_newlines : false
forced_root_block : ''
height: 1000
toolbar:
  - undo redo | save | styleselect | bold italic | forecolor backcolor | image | link
plugins:
  - image
  - link
  - table
  - textcolor colorpicker
  - save
      
style_formats: [
  { title: 'Bold text', inline: 'strong' },
  { title: 'Red text', inline: 'span', styles: { color: '#ff0000' } },
  { title: 'Red header', block: 'h1', styles: { color: '#ff0000' } },
  { title: 'Badge', inline: 'span', styles: { display: 'inline-block', border: '1px solid #2276d2', 'border-radius': '5px', padding: '2px 5px', margin: '0 2px', color: '#2276d2' } },
  { title: 'Table row 1', selector: 'tr', classes: 'tablerow1' }
]
# formats: {
#   alignleft: { selector: 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,table,img', classes: 'left' },
#   aligncenter: { selector: 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,table,img', classes: 'center' },
#   alignright: { selector: 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,table,img', classes: 'right' },
#   alignfull: { selector: 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,table,img', classes: 'full' },
#   bold: { inline: 'span', 'classes': 'bold' },
#   italic: { inline: 'span', 'classes': 'italic' },
#   underline: { inline: 'span', 'classes': 'underline', exact: true },
#   strikethrough: { inline: 'del' },
#   customformat: { inline: 'span', styles: { color: '#00ff00', fontSize: '20px' }, attributes: { title: 'My custom format' }, classes: 'example1' },
# }
# content_css: [
#   '//fast.fonts.net/cssapi/e6dc9b99-64fe-4292-ad98-6974f93cd2a2.css',
#   '//www.tinymce.com/css/codepen.min.css'
# ]